import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import {Modal,Button} from 'react-bootstrap';
export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>판테라의 ICO</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!
        </h1>

        <p className={styles.description}>
          Please login through SNS
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Twitter</h2>
            <div className={styles.twitter_icon}><Image src='/images/twitter.png' height={30} width={40}></Image></div>
          </a>
        </div>
        {/* <div className={styles.img_container}><img className={styles.img_main} src="https://www.superful.xyz/_next/image?url=https%3A%2F%2Fsuperful-assets-prod.s3.amazonaws.com%2Fimages%2F8dd0a15a-1507-43f9-ae60-1928edfb53cd.gif&w=1080&q=75" alt="" /></div> */}
        {/* <Image src='/images/8dd0a15a-1507-43f9-ae60-1928edfb53cd.gif' height={300} width={200}></Image> */}
      </main>
    </div>
    
    </>
  )
}
